events {
    worker_connections 1064; # Can handle up to 1,064 simultaneous connections
}

http {
    #key_zone -> allocate 10mb of ram for index
    #levels=1:2 -> two-level nested folder structure
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=image_cache:10m max_size=1g inactive=24h use_temp_path=off;

    server {
        listen 80;
        

        location / {
            # Only allow downloading images, block PUT/POST requests
            limit_except GET HEAD { deny all; }
            
            # Route traffic to the imgproxy container on port 8080
            proxy_pass http://imgproxy:8080;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # Enable caching using the zone defined above
            proxy_cache image_cache;
            
            # Cache successful image generations (200 OK) for 24 hours
            proxy_cache_valid 200 24h;
            
            # If the image isn't found in MinIO (404), cache that failure for 1 minute
            proxy_cache_valid 404 1m;
            
            # Add a custom header so you can test if the cache is working
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}